// "use client"
import { ThemeProvider } from "@/components/theme-context";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Context
// type Theme = {
//   colors:{
//     primary:string,
//     secondary:string,
//   },
// }

// const defaultTheme : Theme = {
//   colors:{
//     primary:"#007bff",
//     secondary:"6c757d",
//   }
// }

// const ThemeContext = createContext<Theme>(defaultTheme);

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ThemeProvider>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          >
          {children}
        </body>
      </ThemeProvider>
    </html>
  );
}
