"use client"
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { usePathname } from "next/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const metadata: Metadata = {
  title: {
    default:"Next App - Tutorial",
    template:"Next App | %s"
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const navLinks = [
    {name:"Profile",href:"/profile"},
    {name:"Login",href:"/login"},
    {name:"About",href:"/about"},
    {name:"Product",href:"/product"},
  ];

  const pathName = usePathname();

  return (
    <html lang="en">
      <body 
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="text-black text-xl w-[100vw] p-4 bg-blue-400 flex justify-evenly items-center">
          {navLinks.map((link) => {

            const isActive = pathName.startsWith(link.href);

            return (
              <Link className={isActive ? "text-white border-b-red-800 border-b-4 font-bold":"text-black"} href={link.href} key={link.name}>{link.name}</Link>
            )
          })}
        </header>
        {children}
        <footer className="w-[100vw] p-4 bg-pink-400 flex justify-center items-center">
          <h1>Footer Layout</h1>
          </footer>
      </body>
    </html>
  );
}
